---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  interval: 30m
  url: https://weaveworks.github.io/tf-controller/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  chart:
    spec:
      chart: tf-controller
      sourceRef:
        kind: HelmRepository
        name: tf-controller
      version: ">=v0.11.0"
  interval: 60s
  releaseName: tf-controller
  targetNamespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    replicaCount: 1
    resources:
      limits:
        cpu: 1500m
        memory: 2Gi
      requests:
        cpu: 400m
        memory: 64Mi
    awsPackage:
      install: false
    rbac:
      create: false
    caCertValidityDuration: 24h
    certRotationCheckFrequency: 30m
    installCRDs: true
    runner:
      serviceAccount:
        allowedNamespaces:
        - controller-test-1
        - controller-test-2
